version: "3.7"

x-logging: &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  web:
    image: pxsocs/warden:v0.0.1
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/warden:/home/warden
      - ${APP_DATA_DIR}/data:/data
    ports:
      - 5000:5000
